env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 2020
rules:
  linebreak-style:
    - error
    - unix
