env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
    - MemberExpression: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
